package COE817.ClientApplication;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.JFrame;

/**
 *
 * @author Deon
 */
public final class ClientGUI extends javax.swing.JPanel {

    public ClientGUI(ActionListener buttonRegisterEvent) {
        initComponents();
        initRPanel(buttonRegisterEvent);

    }

    public void initRPanel(ActionListener registerEvent) {

        this.R_PanelName.setText("Voter Registration");
        this.R_PanelName.setHorizontalAlignment((int) JPanel.CENTER_ALIGNMENT);
        this.R_PanelName.setVerticalAlignment((int) JPanel.CENTER_ALIGNMENT);

        this.R_Instructions.setText("<html>"
                + "Please enter the following information into the   "
                + "given text field provided below to optain your    "
                + "verification code. Please remember the displayed  "
                + "code as it is required in order to vote." + "</html>");
        this.R_Instructions.setHorizontalAlignment((int) JPanel.CENTER_ALIGNMENT);
        this.R_Instructions.setVerticalAlignment((int) JPanel.CENTER_ALIGNMENT);

        this.R_FirstName.addFocusListener(new FocusListener() {
            String phrase = "First Name...";

            @Override
            public void focusGained(FocusEvent fe) {
                if (R_FirstName.getText().equals(phrase)) {
                    R_FirstName.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent fe) {
                if (R_FirstName.getText().length() <= 1) {
                    R_FirstName.setText(phrase);
                }
            }
        });
        this.R_LastName.addFocusListener(new FocusListener() {
            String phrase = "Last Name...";

            @Override
            public void focusGained(FocusEvent fe) {
                if (R_LastName.getText().equals(phrase)) {
                    R_LastName.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent fe) {
                if (R_LastName.getText().length() <= 1) {
                    R_LastName.setText(phrase);
                }
            }
        });
        this.R_SIN.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent fe) {
                R_SIN.setText("");
            }

            @Override
            public void focusLost(FocusEvent fe) {
                if (R_SIN.getText().length() <= 1) {
                    R_SIN.setText("Social Security Number (SIN)...");
                } else {
                    String tmp = R_SIN.getText().toLowerCase();
                    char check = 'a';
                    while (check <= 'z') {
                        if (tmp.contains(check + ""));
                        {
                            R_SIN.setText("");
                            focusLost(fe);
                            return;
                        }

                    }

                }
            }
        });

        this.R_ConfirmRegs.addActionListener(registerEvent);
    }

    public void resetGUI() {
        R_FirstName.setText("");
        R_LastName.setText("");
        R_SIN.setText("");
        R_LastName.requestFocus();
        R_SIN.requestFocus();
        R_FirstName.requestFocus();
    }

    public String getFirstName() {
        return this.R_FirstName.getText();
    }

    public String getLastName() {
        return this.R_LastName.getText();
    }

    public String getSIN() {
        return this.R_SIN.getText();
    }

    public void setVerficationCode(String verficationID) {
        this.R_Verification.setText(verficationID);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Root = new javax.swing.JPanel();
        RegisterPanel = new javax.swing.JPanel();
        R_PanelName = new javax.swing.JLabel();
        R_Instructions = new javax.swing.JLabel();
        R_FirstName = new javax.swing.JTextField();
        R_LastName = new javax.swing.JTextField();
        R_SIN = new javax.swing.JTextField();
        R_ConfirmRegs = new javax.swing.JButton();
        R_Verification = new javax.swing.JLabel();

        R_PanelName.setText("Voting Registration");

        R_Instructions.setText("Instructions...");

        R_FirstName.setText("First Name...");

        R_LastName.setText("Last Name...");

        R_SIN.setText("Social Security Number (SIN)");

        R_ConfirmRegs.setText("Confirm Registration");

        R_Verification.setText("...");

        javax.swing.GroupLayout RegisterPanelLayout = new javax.swing.GroupLayout(RegisterPanel);
        RegisterPanel.setLayout(RegisterPanelLayout);
        RegisterPanelLayout.setHorizontalGroup(
            RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterPanelLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(R_ConfirmRegs)
                    .addGroup(RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(R_Verification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(R_FirstName)
                        .addComponent(R_LastName, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(R_SIN, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(R_PanelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(R_Instructions, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)))
                .addGap(52, 52, 52))
        );
        RegisterPanelLayout.setVerticalGroup(
            RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(R_PanelName)
                .addGap(18, 18, 18)
                .addComponent(R_Instructions, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(R_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(R_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(R_SIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R_ConfirmRegs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(R_Verification, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout RootLayout = new javax.swing.GroupLayout(Root);
        Root.setLayout(RootLayout);
        RootLayout.setHorizontalGroup(
            RootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RootLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RegisterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        RootLayout.setVerticalGroup(
            RootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RootLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RegisterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton R_ConfirmRegs;
    private javax.swing.JTextField R_FirstName;
    private javax.swing.JLabel R_Instructions;
    private javax.swing.JTextField R_LastName;
    private javax.swing.JLabel R_PanelName;
    private javax.swing.JTextField R_SIN;
    private javax.swing.JLabel R_Verification;
    private javax.swing.JPanel RegisterPanel;
    private javax.swing.JPanel Root;
    // End of variables declaration//GEN-END:variables
}
