package ClientApplication;

import java.awt.event.ActionListener;
import javax.swing.JPanel;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.JButton;

/**
 *
 * @author Deon
 */
public final class VotingGUI extends javax.swing.JPanel {
    
    public VotingGUI(ActionListener buttonRegisterEvent, String options[]) {
        initComponents();
        initRPanel(buttonRegisterEvent, options);
        
    }
    
    public void initRPanel(ActionListener registerEvent, String options[]) {
        
        this.V_PanelName.setText("Voting Station");
        this.V_PanelName.setHorizontalAlignment((int) JPanel.CENTER_ALIGNMENT);
        this.V_PanelName.setVerticalAlignment((int) JPanel.CENTER_ALIGNMENT);
        
        this.V_Instructions.setText("<html>"
                + "Please enter your verification code below in the    "
                + "given text field. The verification code be required "
                + "to authenticate your vote." + "</html>");
        this.V_Instructions.setHorizontalAlignment((int) JPanel.CENTER_ALIGNMENT);
        this.V_Instructions.setVerticalAlignment((int) JPanel.CENTER_ALIGNMENT);
        
        this.V_VerificationCode.addFocusListener(new FocusListener() {
            String phrase = "Verification Code...";
            
            @Override
            public void focusGained(FocusEvent fe) {
                if (V_VerificationCode.getText().equals(phrase)) {
                    V_VerificationCode.setText("");
                }
            }
            
            @Override
            public void focusLost(FocusEvent fe) {
                if (V_VerificationCode.getText().length() <= 1) {
                    V_VerificationCode.setText(phrase);
                }
            }
        });
        
        V_Options.setModel(new javax.swing.DefaultComboBoxModel<>(options));
        
        this.V_Vote.addActionListener(registerEvent);
    }
    
    public void resetGUI() {
        V_VerificationCode.setText("");
        V_VerificationCode.requestFocus();
    }
    
    public String getVerification() {
        return this.V_VerificationCode.getText();
    }
    
    public void setVerficationCode(String verficationID) {
        this.V_Verification.setText(verficationID);
    }

    public int getVote() {
        return V_Options.getSelectedIndex();
    }

    public void setButtonText(String s) {
        V_Vote.setText(s);
    }

    public JButton getButton() {
        return V_Vote;
    }
    
    public void setVCfield(String s) {
        V_VerificationCode.setText(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VotingPanel = new javax.swing.JPanel();
        V_PanelName = new javax.swing.JLabel();
        V_Instructions = new javax.swing.JLabel();
        V_VerificationCode = new javax.swing.JTextField();
        V_Vote = new javax.swing.JButton();
        V_Verification = new javax.swing.JLabel();
        V_Options = new javax.swing.JComboBox<>();

        V_PanelName.setText("Voting Station");

        V_Instructions.setText("Instructions...");

        V_VerificationCode.setText("Verification Code...");

        V_Vote.setText("Confirm Vote");

        V_Verification.setText("...");

        V_Options.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout VotingPanelLayout = new javax.swing.GroupLayout(VotingPanel);
        VotingPanel.setLayout(VotingPanelLayout);
        VotingPanelLayout.setHorizontalGroup(
            VotingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VotingPanelLayout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(VotingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(V_Options, 0, 274, Short.MAX_VALUE)
                    .addComponent(V_Vote)
                    .addComponent(V_Verification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(V_VerificationCode)
                    .addComponent(V_PanelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(V_Instructions, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
                .addGap(52, 52, 52))
        );
        VotingPanelLayout.setVerticalGroup(
            VotingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VotingPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(V_PanelName)
                .addGap(18, 18, 18)
                .addComponent(V_Instructions, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(V_VerificationCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(V_Options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(V_Vote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(V_Verification, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VotingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VotingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel V_Instructions;
    private javax.swing.JComboBox<String> V_Options;
    private javax.swing.JLabel V_PanelName;
    private javax.swing.JLabel V_Verification;
    private javax.swing.JTextField V_VerificationCode;
    private javax.swing.JButton V_Vote;
    private javax.swing.JPanel VotingPanel;
    // End of variables declaration//GEN-END:variables
}
